//! MSEC ("metadata SEC") text serializer — a faithful port of
//! `server/serialization/MSECWriter.cs` (`MSECSerializer`) plus the bits of
//! `server/Sector.cs` / `server/SectorStylesheet.cs` it leans on (route hex
//! normalization, the allegiance grouping sort, and the stylesheet colour
//! cascade).
//!
//! MSEC is the legacy text the reference's `sec2pdf` consumes: a sector header,
//! the `a`–`p` subsector list, then `ally`/`route`/`label`/`border` lines grouped
//! by allegiance. The format is line-oriented and **byte-significant**, so this
//! mirrors the reference exactly, including:
//!
//! * **Line endings are CRLF** — the reference writes via `StringWriter` whose
//!   `NewLine` is the Windows host's `Environment.NewLine`.
//! * **Route hex normalization** (`FixHex`): out-of-sector hex columns/rows
//!   (`<1` or `>32`/`>40`) are folded back into `01..32` / `01..40` with a
//!   compensating sector offset, so `Start="0001"` emits `-1 0 3201`.
//! * **Allegiance grouping order** reproduces .NET's `List<T>.Sort` — an
//!   *unstable* introspective sort — so same-key items (e.g. several `ImDd`
//!   borders) come out in the reference's order, not source order.
//! * **Colours** resolve through the sector stylesheet cascaded over the default
//!   `res/styles/otu.css`, then round-trip through the reference's
//!   `ColorTranslator` (named colours stay named, hex stays hex, all lowercased).
//!
//! The caller supplies the already-parsed [`crate::metadata::SectorMetadata`]
//! plus the sector display name and (usually empty) header fields; this module
//! has no I/O.

use std::fmt::Write as _;

use crate::astrometrics::{parse_hex, SECTOR_HEIGHT, SECTOR_WIDTH};
use crate::metadata::{MetaAllegiance, MetaBorder, MetaLabel, MetaRoute, SectorMetadata};
use crate::world_util::allegiance_name;

/// Reference uses `Environment.NewLine` (CRLF) on its Windows host.
const NL: &str = "\r\n";

/// The default sector stylesheet (`res/styles/otu.css`), cascaded *under* any
/// per-sector `<Stylesheet>` — matches `Sector.s_defaultStyleSheet`.
const OTU_CSS: &str = include_str!("../../../res/styles/otu.css");

/// Optional sector header fields (`domain`, `alpha`..`delta`). These only ever
/// come from MSEC *input* in the reference (never from a sector's `.xml`), so for
/// XML-loaded sectors they are all `None`; carried here to keep the port faithful.
#[derive(Debug, Default, Clone)]
pub struct MsecHeader {
    pub domain: Option<String>,
    pub alpha: Option<String>,
    pub beta: Option<String>,
    pub gamma: Option<String>,
    pub delta: Option<String>,
}

/// Serialize a sector's metadata as MSEC text. `name` is the sector's primary
/// display name (`sector.Names[0].Text`); `now` is the ISO-8601 timestamp for the
/// header comment (callers normalize it away for comparison).
pub fn write_msec(name: &str, header: &MsecHeader, meta: &SectorMetadata, now: &str) -> String {
    let mut out = String::new();

    // Header.
    out.push_str("# Generated by https://travellermap.com");
    out.push_str(NL);
    out.push_str("# ");
    out.push_str(now);
    out.push_str(NL);
    out.push_str(NL);

    // Sector name + optional header fields.
    push_line(&mut out, &format!("sector {name}"));
    if let Some(v) = nonempty(&header.domain) {
        push_line(&mut out, &format!("domain {v}"));
    }
    if let Some(v) = nonempty(&header.alpha) {
        push_line(&mut out, &format!("alpha {v}"));
    }
    if let Some(v) = nonempty(&header.beta) {
        push_line(&mut out, &format!("beta {v}"));
    }
    if let Some(v) = nonempty(&header.gamma) {
        push_line(&mut out, &format!("gamma {v}"));
    }
    if let Some(v) = nonempty(&header.delta) {
        push_line(&mut out, &format!("delta {v}"));
    }
    out.push_str(NL);

    // Subsectors (16 slots a..p, by Index letter A..P).
    if !meta.subsectors.is_empty() {
        push_line(&mut out, "# Subsectors");
        push_line(&mut out, "#");
        for i in 0..16u8 {
            let letter = (b'a' + i) as char;
            let index = (b'A' + i) as char;
            let ss = meta
                .subsectors
                .iter()
                .find(|s| s.index.chars().next().map(|c| c.to_ascii_uppercase()) == Some(index));
            match ss {
                Some(s) if !s.name.is_empty() => {
                    push_line(&mut out, &format!("{letter} {}", s.name))
                }
                _ => push_line(&mut out, &format!("{letter}")),
            }
        }
        out.push_str(NL);
    }

    // Build the combined, allegiance-grouped item list. Order matches the
    // reference's AddRange sequence: allegiances (none from XML), borders +
    // regions (source order), routes, labels.
    let sheet = Stylesheet::cascade(meta.stylesheet.as_deref());
    let mut items: Vec<Item> = Vec::new();
    for b in borders_and_regions(meta) {
        items.push(Item::Border(b));
    }
    for r in &meta.routes {
        items.push(Item::Route(r));
    }
    for l in &meta.labels {
        items.push(Item::Label(l));
    }

    // Group by (allegiance, type). The reference uses .NET's *unstable*
    // `List<T>.Sort`, so the relative order of equal-key items (same allegiance +
    // same kind) is a sort-internal artifact that is impractical to reproduce
    // byte-for-byte and brittle across runtimes. We therefore emit a **stable**
    // grouping (source/document order preserved within each group) — the group
    // set, group order, group headers, and every line's text are identical to the
    // reference; only the intra-group line order can differ, and the compat suite
    // normalizes that away (see `compat_suite::msec_text`).
    items.sort_by(compare_allegiances);

    let mut first = true;
    let mut group_code: Option<String> = None;
    for item in &items {
        let code = item.allegiance().map(str::to_owned);
        if first || code != group_code {
            first = false;
            group_code = code.clone();
            let group_name = code
                .as_deref()
                .and_then(|c| resolve_allegiance_name(c, &meta.local_allegiances));
            out.push_str(NL);
            match group_name {
                Some(n) => {
                    out.push_str("# ");
                    push_line(&mut out, &n);
                    push_line(&mut out, "#");
                }
                None => {
                    push_line(&mut out, "# Other");
                    push_line(&mut out, "#");
                }
            }
        }

        match item {
            Item::Border(b) => write_border(&mut out, b, &meta.local_allegiances, &sheet),
            Item::Route(r) => write_route(&mut out, r, &sheet),
            Item::Label(l) => write_label(&mut out, l),
        }
    }

    out
}

/// Borders followed by regions, but restored to combined document order via the
/// shared `seq` index — matches the reference `BordersAndRegions`.
fn borders_and_regions(meta: &SectorMetadata) -> Vec<&MetaBorder> {
    let mut v: Vec<&MetaBorder> = meta.borders.iter().chain(meta.regions.iter()).collect();
    v.sort_by_key(|b| b.seq);
    v
}

fn resolve_allegiance_name(code: &str, local: &[MetaAllegiance]) -> Option<String> {
    // Sector-local <Allegiance> overrides win, else the stock code table.
    local
        .iter()
        .find(|a| a.code == code)
        .map(|a| a.name.clone())
        .filter(|n| !n.is_empty())
        .or_else(|| allegiance_name(code))
}

fn write_route(out: &mut String, route: &MetaRoute, sheet: &Stylesheet) {
    out.push_str("route ");

    let (start_hex, sox, soy) = fix_hex(&route.start, route.start_offset_x, route.start_offset_y);
    let (end_hex, eox, eoy) = fix_hex(&route.end, route.end_offset_x, route.end_offset_y);

    if sox != 0 || soy != 0 {
        write!(out, "{sox} {soy} ").unwrap();
    }
    write!(out, "{start_hex} ").unwrap();
    if eox != 0 || eoy != 0 {
        write!(out, "{eox} {eoy} ").unwrap();
    }
    out.push_str(&end_hex);

    let color = route
        .color
        .clone()
        .or_else(|| sheet.color("route", route.allegiance.as_deref()));
    if let Some(c) = color {
        out.push(' ');
        out.push_str(&to_html_color(&c));
    }
    out.push_str(NL);
}

fn write_label(out: &mut String, label: &MetaLabel) {
    let lines: Vec<&str> = label.text.split('\n').collect();
    const LINE_OFFSET: i32 = -60;
    let mut offset = -(LINE_OFFSET * (lines.len() as i32 - 1)) / 2;
    for line in lines {
        if !line.is_empty() {
            out.push_str("label ");
            out.push_str(&label.hex);
            if offset != 0 {
                out.push('/');
                // Reference format "+0;-0": explicit sign, no leading zeros.
                write!(out, "{offset:+}").unwrap();
            }
            out.push(' ');
            out.push_str(line);
            out.push_str(NL);
        }
        offset += LINE_OFFSET;
    }
}

fn write_border(
    out: &mut String,
    border: &MetaBorder,
    local: &[MetaAllegiance],
    sheet: &Stylesheet,
) {
    let alleg_name = border
        .allegiance
        .as_deref()
        .and_then(|c| resolve_allegiance_name(c, local));

    if border.show_label && (border.label.is_some() || alleg_name.is_some()) {
        out.push_str("label ");
        out.push_str(&label_position_hex(border));
        out.push(' ');
        out.push_str(
            border
                .label
                .as_deref()
                .or(alleg_name.as_deref())
                .unwrap_or(""),
        );
        out.push_str(NL);
    }

    out.push_str("border ");
    out.push_str(&border.hexes.join(" "));

    let color = border
        .color
        .clone()
        .or_else(|| sheet.color("border", border.allegiance.as_deref()));
    if let Some(c) = color {
        out.push(' ');
        out.push_str(&to_html_color(&c));
    }
    out.push_str(NL);
}

/// `Border.LabelPositionHex`: the explicit `LabelPosition` attribute, else the
/// bounding-box centre of the path (`((min+max+1)/2)` per axis), as a `0xyy` hex.
fn label_position_hex(border: &MetaBorder) -> String {
    if let Some(p) = nonempty(&border.label_position) {
        return p;
    }
    let coords: Vec<(i32, i32)> = border.hexes.iter().filter_map(|h| parse_hex(h)).collect();
    if coords.is_empty() {
        return "0000".to_string();
    }
    let (min_x, max_x) = coords
        .iter()
        .fold((i32::MAX, i32::MIN), |(a, b), &(x, _)| (a.min(x), b.max(x)));
    let (min_y, max_y) = coords
        .iter()
        .fold((i32::MAX, i32::MIN), |(a, b), &(_, y)| (a.min(y), b.max(y)));
    format!(
        "{:02}{:02}",
        (min_x + max_x + 1) / 2,
        (min_y + max_y + 1) / 2
    )
}

/// Normalize an out-of-sector hex into `01..SectorWidth` / `01..SectorHeight`,
/// adjusting the offset to compensate (port of `Route.FixHex`).
fn fix_hex(hex: &str, mut ox: i32, mut oy: i32) -> (String, i32, i32) {
    let Some((mut x, mut y)) = parse_hex(hex) else {
        return (hex.to_string(), ox, oy);
    };
    if x < 1 {
        x += SECTOR_WIDTH;
        ox -= 1;
    } else if x > SECTOR_WIDTH {
        x -= SECTOR_WIDTH;
        ox += 1;
    }
    if y < 1 {
        y += SECTOR_HEIGHT;
        oy -= 1;
    } else if y > SECTOR_HEIGHT {
        y -= SECTOR_HEIGHT;
        oy += 1;
    }
    (format!("{x:02}{y:02}"), ox, oy)
}

fn push_line(out: &mut String, s: &str) {
    out.push_str(s);
    out.push_str(NL);
}

fn nonempty(s: &Option<String>) -> Option<String> {
    s.as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
}

// --- Allegiance grouping (item kinds + comparator + .NET introsort) ----------

enum Item<'a> {
    Border(&'a MetaBorder),
    Route(&'a MetaRoute),
    Label(&'a MetaLabel),
}

impl Item<'_> {
    fn allegiance(&self) -> Option<&str> {
        match self {
            Item::Border(b) => b.allegiance.as_deref(),
            Item::Route(r) => r.allegiance.as_deref(),
            Item::Label(l) => l.allegiance.as_deref(),
        }
    }

    /// The reference sorts by `item.GetType().ToString()` as the in-allegiance
    /// tiebreak: the CLR type full names (`Maps.Border` < `Maps.Label` <
    /// `Maps.Region` < `Maps.Route`). We don't distinguish Region from Border at
    /// this layer (both are `MetaBorder`), but the only mixed-type groups here
    /// pair Border with Route, and `Maps.Border` < `Maps.Route` is preserved.
    fn type_name(&self) -> &'static str {
        match self {
            Item::Border(_) => "Maps.Border",
            Item::Label(_) => "Maps.Label",
            Item::Route(_) => "Maps.Route",
        }
    }
}

/// Port of `MSECSerializer.CompareAllegiances`: order by allegiance code (a
/// `None` allegiance sorts first), tiebreak by CLR type name; equal items compare
/// `Equal`. Used with a **stable** sort so equal-key items keep source order
/// (see the grouping note in [`write_msec`]).
fn compare_allegiances(a: &Item, b: &Item) -> std::cmp::Ordering {
    use std::cmp::Ordering;
    match (a.allegiance(), b.allegiance()) {
        (None, None) => a.type_name().cmp(b.type_name()),
        (None, Some(_)) => Ordering::Less,
        (Some(_), None) => Ordering::Greater,
        (Some(x), Some(y)) if x == y => a.type_name().cmp(b.type_name()),
        (Some(x), Some(y)) => x.cmp(y),
    }
}

// --- Colours -----------------------------------------------------------------

/// Round-trip a stylesheet/border/route colour value through the reference's
/// `ColorTranslator.ToHtml(ColorTranslator.FromHtml(value)).ToLowerInvariant()`.
/// For the colour vocabulary in use (named CSS colours + `#rrggbb` hex), this is
/// a straight lowercase: a recognized named colour round-trips to its lowercased
/// canonical name, and hex stays hex.
fn to_html_color(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}

// --- Minimal CSS cascade (port of SectorStylesheet) --------------------------

struct Stylesheet {
    rules: Vec<Rule>,
}

struct Rule {
    selectors: Vec<Selector>,
    declarations: Vec<(String, String)>,
}

struct Selector {
    element: String,
    code: Option<String>,
}

impl Stylesheet {
    /// Build the effective sheet: the default `otu.css` first, then the optional
    /// per-sector CSS — matching the reference's parent→child chain walk, where a
    /// same-specificity sector rule (seen later) overrides the default.
    fn cascade(sector_css: Option<&str>) -> Stylesheet {
        let mut rules = parse_stylesheet(OTU_CSS);
        if let Some(css) = sector_css {
            rules.extend(parse_stylesheet(css));
        }
        Stylesheet { rules }
    }

    /// Resolve the `color` property for `element`/`code`, returning the raw value
    /// string (caller round-trips it through `to_html_color`).
    fn color(&self, element: &str, code: Option<&str>) -> Option<String> {
        // (match-rank, value); a later rule with rank >= the current one wins.
        let mut best: Option<(i32, String)> = None;
        for rule in &self.rules {
            for sel in &rule.selectors {
                let rank = match_selector(element, code, sel);
                if rank == 0 {
                    continue;
                }
                for (prop, val) in &rule.declarations {
                    if !prop.eq_ignore_ascii_case("color") || val.is_empty() {
                        continue;
                    }
                    if best.as_ref().is_none_or(|(r, _)| rank >= *r) {
                        best = Some((rank, val.clone()));
                    }
                }
            }
        }
        best.map(|(_, v)| v)
    }
}

fn match_selector(element: &str, code: Option<&str>, sel: &Selector) -> i32 {
    if element != sel.element {
        return 0;
    }
    match &sel.code {
        None => 1,
        Some(c) => {
            if code == Some(c.as_str()) {
                2
            } else {
                0
            }
        }
    }
}

/// Parse the small CSS grammar used by the sector stylesheets:
/// `selector ( ',' selector )* '{' (ident ':' value ';'?)* '}'`, with `/* … */`
/// comments and `\ ` escapes in selector codes. A faithful-enough port of
/// `SectorStylesheet.Parser` for the `color` property we read.
fn parse_stylesheet(src: &str) -> Vec<Rule> {
    let chars: Vec<char> = src.chars().collect();
    let mut p = Parser {
        chars: &chars,
        pos: 0,
    };
    let mut rules = Vec::new();
    p.ws();
    while p.peek().is_some() {
        let Some(rule) = p.parse_rule() else { break };
        rules.push(rule);
        p.ws();
    }
    rules
}

struct Parser<'a> {
    chars: &'a [char],
    pos: usize,
}

impl Parser<'_> {
    fn peek(&self) -> Option<char> {
        self.chars.get(self.pos).copied()
    }
    fn bump(&mut self) -> Option<char> {
        let c = self.peek();
        if c.is_some() {
            self.pos += 1;
        }
        c
    }

    /// Skip whitespace and `/* … */` comments.
    fn ws(&mut self) {
        while let Some(c) = self.peek() {
            match c {
                '\t' | '\n' | '\r' | ' ' => {
                    self.pos += 1;
                }
                '/' if self.chars.get(self.pos + 1) == Some(&'*') => {
                    self.pos += 2;
                    while self.pos < self.chars.len() {
                        if self.chars[self.pos] == '*' && self.chars.get(self.pos + 1) == Some(&'/')
                        {
                            self.pos += 2;
                            break;
                        }
                        self.pos += 1;
                    }
                }
                _ => return,
            }
        }
    }

    fn parse_rule(&mut self) -> Option<Rule> {
        let selectors = self.parse_selector_list();
        if selectors.is_empty() {
            return None;
        }
        if self.peek() != Some('{') {
            return None;
        }
        self.bump();
        let declarations = self.parse_declaration_list();
        self.ws();
        if self.peek() == Some('}') {
            self.bump();
        }
        Some(Rule {
            selectors,
            declarations,
        })
    }

    fn parse_selector_list(&mut self) -> Vec<Selector> {
        let mut list = Vec::new();
        loop {
            self.ws();
            let Some(sel) = self.parse_selector() else {
                break;
            };
            list.push(sel);
            self.ws();
            if self.peek() == Some(',') {
                self.bump();
                continue;
            }
            break;
        }
        list
    }

    fn parse_selector(&mut self) -> Option<Selector> {
        let element = self.ident()?;
        let code = if self.peek() == Some('.') {
            self.bump();
            self.ident()
        } else {
            None
        };
        Some(Selector { element, code })
    }

    fn parse_declaration_list(&mut self) -> Vec<(String, String)> {
        let mut decls = Vec::new();
        loop {
            self.ws();
            match self.peek() {
                Some('}') | None => break,
                _ => {}
            }
            let Some(prop) = self.ident() else { break };
            self.ws();
            if self.peek() != Some(':') {
                break;
            }
            self.bump();
            self.ws();
            let value = self.value().unwrap_or_default();
            decls.push((prop, value));
            self.ws();
            if self.peek() == Some(';') {
                self.bump();
            }
        }
        decls
    }

    /// An identifier; `\ ` escapes a literal space (e.g. `Core\ Route`).
    fn ident(&mut self) -> Option<String> {
        let mut s = String::new();
        while let Some(c) = self.peek() {
            if c == '\\' {
                self.bump();
                if let Some(esc) = self.bump() {
                    s.push(esc);
                }
            } else if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                s.push(c);
                self.bump();
            } else {
                break;
            }
        }
        if s.is_empty() {
            None
        } else {
            Some(s)
        }
    }

    /// A property value: an identifier, a number, or a `#rrggbb` colour.
    fn value(&mut self) -> Option<String> {
        match self.peek() {
            Some('#') => {
                let mut s = String::from("#");
                self.bump();
                for _ in 0..6 {
                    match self.peek() {
                        Some(c) if c.is_ascii_hexdigit() => {
                            s.push(c);
                            self.bump();
                        }
                        _ => break,
                    }
                }
                Some(s)
            }
            Some(c) if c.is_ascii_digit() => {
                let mut s = String::new();
                while let Some(c) = self.peek() {
                    if c.is_ascii_digit() || c == '.' {
                        s.push(c);
                        self.bump();
                    } else {
                        break;
                    }
                }
                Some(s)
            }
            _ => self.ident(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fix_hex_normalizes_outsector_columns() {
        // "0001" -> column 0 folds to 32 with offsetX -1.
        assert_eq!(fix_hex("0001", 0, 0), ("3201".to_string(), -1, 0));
        // "3324" -> column 33 folds to 1 with offsetX +1.
        assert_eq!(fix_hex("3324", 0, 0), ("0124".to_string(), 1, 0));
        // In-range hexes are untouched.
        assert_eq!(fix_hex("2102", 0, 0), ("2102".to_string(), 0, 0));
    }

    #[test]
    fn stylesheet_cascade_sector_overrides_default() {
        let sheet = Stylesheet::cascade(Some(
            "border.DaCf { color: lightblue; }\nroute.DaCf { color: lightgreen; }",
        ));
        assert_eq!(
            sheet.color("border", Some("DaCf")).as_deref(),
            Some("lightblue")
        );
        assert_eq!(
            sheet.color("route", Some("DaCf")).as_deref(),
            Some("lightgreen")
        );
        // otu.css default still resolves.
        assert_eq!(
            sheet.color("border", Some("ImDd")).as_deref(),
            Some("#E32736")
        );
        assert_eq!(
            sheet.color("route", Some("ZhCo")).as_deref(),
            Some("lightblue")
        );
        // No bare-route rule -> None for an unstyled "Other" route.
        assert_eq!(sheet.color("route", None), None);
    }

    #[test]
    fn html_color_lowercases() {
        assert_eq!(to_html_color("#E32736"), "#e32736");
        assert_eq!(to_html_color("lightblue"), "lightblue");
        assert_eq!(to_html_color("blue"), "blue");
    }
}
